### ISSUE TITLE
CD direto no Heroko após testes bem-sucedidos no Actions

### ISSUE THREAD

**Issue by vpdasilva** [cassiobotaro/do_zero_a_implantacao#92]
A ideia aqui seria aumentar a esteira, encurtando o tempo de trabalho manual, e fazer o desenvolvedor ganhar tempo.

Após completar o processo "Mandando um fogueto para o espaço", com tudo funcionando corretamente, mantenha seu terminal aberto e estejaa dentro do seu ambiente (.venv). Então rode o comando <code>heroku auth:token</code> e será mostrado a chave da API do seu projeto no Heroku; copie ele, pois vamos ultiliza-lo em breve.
Abra o seu repositório no navegador e vá na aba"Settings", depois procure por "Secrets" no menu lateral (esquerda) e expanda-o, então selecione "Actions". A página carregará e você verá a opção "New repository secret", clique nele. A página irá carregar novamente e você verá dois campos "YOUR_NAME_SECRETE", nele escreva <code>HEROKU_API_KEY</code> e no segundo campo, coloque a chave que gerou do seu ambiente (com o comando<code>heroku auth:token</code>) e adicione o segredo (Add Secret).
Agora crie outro segredo com o nome de "HEROKU_EMAIL" e cole seu e-mail no segundo campo do segredo e salve como fez antes.
Agora vá para o seu projeto no VSCode e abra o arquivo "main.yml", nele, cole o código a seguir, logo abaixo do "run: python -m pytest .", identando com os "steps":
```
- uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME" #Ex: nomedaaplicacaogerada.herokuapp.com
          heroku_email: "HEROKU_EMAIL"
```
Substitua o nome da sua aplicação (#Ex: nomedaaplicacaogerada.herokuapp.com). Se você não lembra, volte no seu terminal e escreva <code>heroku apps:info</code> e pegue o link similar a: https://nomedaaplicacaogerada.herokuapp.com
Agora só salvar seu arquivo, <code>git add .</code> , depois o <code>git commit -m "Adiciona ação de deploy para Heroku"</code> e dar <code>git push</code> no seu terminar e o Actions irá fazer o Deploy da sua API para o Heroku automaticamente.
(Obrigado Akhileshns e seu repositório akhileshns/heroku-deploy)
